name: polywallet
description: A fast and open-source wallet for all the chains and tokens out there.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bip39: ^1.0.6
  provider: ^6.0.2
  flutter_secure_storage: ^5.0.2
  alan: ^0.40.2+1
  web3dart: ^2.3.5
  solana: ^0.18.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
